/**:
  ros__parameters:
    port: /dev/ttyACM0
    baudrate: 115200
    timeout_ms: 50

    cmd_vel_topic: /cmd_vel
    odom_topic: /odom
    odom_pub_hz: 50

    reset_on_startup: true
    reset_pulse_ms: 100
    reset_boot_wait_ms: 1500

    debug: true
    cmd_vel_timeout_ms: 500